classification: electrical
color: ''
description_extra: ''
description_main: ''
id: electrical_light_panel_600_mm_x_600_mm_baumatic_bx_lc6060_36w
manufacturer: baumatic
part_number: bx_lc6060_36w
size: 600_mm_x_600_mm
type: light_panel
